[package]
name = "transient_map"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DouglasDwyer/transient_map"
readme = "README.md"
description = """
Hashmap with eviction of unused elements.
"""

[dependencies]
